[package]
name = "cbindgen-demo"
version = "0.1.0"
authors = ["Eric Seppanen <eds@reric.net>"]
edition = "2018"
license = "MIT"

[lib]
name = "demo"
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[build-dependencies]
cbindgen = "0.19"

